import { Product } from "../interfaces/products/product";

export const myJson: Product[] = [
  {
    id: "1",
    name: "chiodi",
    description: "dei chiodi",
    image: [`test`],
    quantity: 4,
    price: 2,
    available: true,
    evidence: false,
    discount: 5,
    category: [`home`, `bricolage`],
  },
  {
    id: 2,
    name: "scarpe",
    price: 20,
    description: "delle scarpe",
    image: [``],
    quantity: 8,
    available: true,
    evidence: false,
    discount: 0,
    category: [`dress`],
  },
  {
    id: 3,
    name: "martello",
    price: 15,
    description: "un martello",
    image: [`test`, `test2`],
    quantity: 2,
    available: true,
    evidence: false,
    discount: 5,
    category: [`bricolage`],
  },
];
