name: CI Staging

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use latest node.js version
        uses: actions/setup-node@v2.1.5
        with:
          check-latest: true
      - name: Install serverless plugin
        run: |
          npm install -g serverless
          
      - name: Install dependencies
        run: |
          npm ci
      - name: Deploy
        run: |
          serverless
